title:  GeoERA GIP
email:
description: >- # this means to ignore newlines until "baseurl:"
   Integrating information and knowledge to support sustainable use of the subsurface.
twitter_username: Geo_ERA
github_username: GeoEra-GIP
og_image: "https://i0.wp.com/geoera.eu/wp-content/uploads/2019/08/information-platform-logo.png"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: air
remote_theme: mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
search: true
breadcrumbs: false
words_per_minute: 180
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 'Europe/London'
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-remote-theme

author:
  name: 'GeoERA GIP'
  avatar: 'https://i0.wp.com/geoera.eu/wp-content/uploads/2019/08/information-platform-logo.png'
  bio: 'Integrating information and knowledge to support sustainable use of the subsurface.'
  links:
    - label: 'Website'
      icon: 'fas fa-fw fa-link'
      url: 'https://geoera.eu/projects/gip-p/'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/Geo_ERA'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/GeoEra-GIP'
    - label: 'Linkedin'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/company/geoera/'

footer:
  links:
    - label: 'Website'
      icon: 'fas fa-fw fa-link'
      url: 'https://geoera.eu/projects/gip-p/'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/Geo_ERA'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/GeoEra-GIP'
    - label: 'Linkedin'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/company/geoera/'

defaults:
   # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: splash
      author_profile: true
 # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

repository: 'GeoEra-GIP/geoera-gip.github.io'

comments:
  provider: 'utterances'
  utterances:
    theme: 'github-light'
    issue_term: 'pathname'
    label: 'comments'

theme: jekyll-theme-minimal
